[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
presale = "GdrDqxCtedMNdXt2JqEUYZiDiy2F7p5snKTgRszj2C17"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/harry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60 # Increase the wait time (in seconds)