[features]
seeds = false
skip-lint = false
[programs.devnet]
token_presale = "8k8wGkeGBRkHbniT7PYpaS9zPC5jDhVbpG6jx9k2u9AG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
